# Standard Netflix Eureka Service Registry Port
server.port=8761

spring.application.name=discovery-service

# Since this application IS the Eureka server, it should not register itself as a client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable aggressive eviction in development to prevent premature service deregistrations
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

# Friendly banner logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
